name: ntu
channels:
  - conda-forge
  - defaults
dependencies:
    - python >=3.7
    - numpy
    - pandas
    - h5py
    - pip
    - pip:
        - git+https://github.com/pnewstein/neurotraceutils.git@master
